"""Module with spacing settings."""

HORIZONTAL_PIXELS_PER_LETTER = 7
VERTICAL_PIXELS_PER_LINE = 14

COLUMN_WIDTH = 180
COLUMN_VERTICAL_MARGIN = 10

COLUMN_CONTAINER_HORIZONTAL_MARGIN = 10
COLUMN_CONTAINER_VERTICAL_MARGIN = 10
COLUMN_CONTAINER_CHILD_SPACING = 10

TABLE_HORIZONTAL_MARGIN = 10
TABLE_VERTICAL_MARGIN = 10
TABLE_CHILD_SPACING = 10

TABLE_X_SPACING = 200
TABLE_Y_SPACING = 100
